# Site settings
title: "montqrewa.xyz"
description: > 
   Perfektion von Zukunft, Technologie und Kunst.

author: montqrewa.xyz
email: ferhat@ekofi.science
twitter_username: 
github_username: 

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://montqrewa.xyz" # the base hostname & protocol for your site

google_analytics_id: UA-112209397-5
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

